name: SamiMod Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          bash gradlew build
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SamiMod-Jar
          path: build/libs/*.jar
          
